#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          off 

# yabai -m config window_placement             second_child
# yabai -m config window_topmost               off
# yabai -m config window_opacity               off
# yabai -m config window_shadow                off

yabai -m config insert_feedback_color        0xaad75f5f
yabai -m config split_ratio                  0.5
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

yabai -m config top_padding     0 
yabai -m config bottom_padding  0 
yabai -m config left_padding    0 
yabai -m config right_padding   0 
yabai -m config window_gap      4


# https://github.com/koekeishiya/yabai/issues/330
# By default leave windows in all spaces of main screen alone
yabai -m query --displays --display 1 |
  jq '.spaces[]' |
  xargs -I{} yabai -m space {} --layout float

# Let yabai manage windows on second screen 
yabai -m query --displays --display 2 |
  jq '.spaces[]' |
  xargs -I{} yabai -m space {} --layout bsp

# yabai -m config layout float           # default for all spaces (leave window layout alone)
# yabai -m config --space 1 layout bsp   # terminal
yabai -m config --space 2 layout bsp   # Apps
yabai -m config --space 3 layout bsp   # Apps (Chrome)
# yabai -m config --space 4 layout float # space 4 IDE
# yabai -m config --space 5 layout bsp   # Misc
# yabai -m config --space 6 layout bsp   # Work

# disabled apps
yabai -m rule --add app="^LICEcap"                manage=off


# yabai -m rule --add app=Emacs                  manage=on
# yabai -m rule --add app=iTerm2                 manage=on
# yabai -m rule --add app="^Zoom"                manage=off
# yabai -m rule --add app="^Better Touch Tool"   manage=off
# yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
# yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
# yabai -m rule --add label="System Preferences" app="^System Preferences$" manage=off
# yabai -m rule --add label="App Store" app="^App Store$" manage=off
# yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
# yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
# yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
# yabai -m rule --add label="Transmission" app="^Transmission$" manage=off
# yabai -m rule --add label="VirtualBox" app="^VirtualBox$" manage=off

# Turn all off since all we need is Desktop switching without transitions
# yabai -m rule --add app="*"     manage=off
# yabai -m rule --add label="*"   manage=off

