#!/usr/bin/env sh

# global settings
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          off 

yabai -m config window_placement             second_child
yabai -m config window_topmost               on
yabai -m config window_opacity               on
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.95
yabai -m config window_opacity_duration      0
yabai -m config window_shadow                off

yabai -m config insert_feedback_color        0xaad75f5f
yabai -m config split_ratio                  0.5
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config top_padding                  0
yabai -m config bottom_padding               0
yabai -m config left_padding                 0
yabai -m config right_padding                0
yabai -m config window_gap                   3

# float vs. bsp
yabai -m config layout float           # default for all spaces
yabai -m config --space 1 layout bsp   # terminal
yabai -m config --space 2 layout float # space 2 emacs
yabai -m config --space 3 layout bsp   # Apps
yabai -m config --space 4 layout float # space 4 IDE
yabai -m config --space 5 layout bsp   # Misc
yabai -m config --space 6 layout bsp   # Cypress

# disabled apps
yabai -m rule --add app=Emacs                  manage=on
yabai -m rule --add app=iTerm2                 manage=on
yabai -m rule --add app="^Zoom"                manage=off
yabai -m rule --add app="^Better Touch Tool"   manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="System Preferences" app="^System Preferences$" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
yabai -m rule --add label="Transmission" app="^Transmission$" manage=off
yabai -m rule --add label="VirtualBox" app="^VirtualBox$" manage=off
