#!/usr/bin/env node

// @ts-check
'use strict'

const { execSync: exec } = require('child_process')

function timezoneOffset() {
  const date = new Date()
  const timezoneDelta = -date.getTimezoneOffset() / 60
  const timezoneString = `-0${Math.abs(timezoneDelta)}00`
  return [timezoneDelta, timezoneString]
}

const [timezoneDelta, timezoneString] = timezoneOffset()

// GIT_COMMITTER_DATE="Wed 23 June 2021 22:09:09 MDT" git commit --amend --no-edit --date "Wed 23 June 2021 22:09:09 MDT"

const yesterday = new Date(
  Date.now() - 12 * 60 * 60000 + timezoneDelta * 60 * 60000
)
const addedString = yesterday.toUTCString() + timezoneString
const cmd =
  `GIT_AUTHOR_DATE="${addedString}" GIT_COMMITTER_DATE="${addedString}" ` +
  `git commit --amend --no-edit --date="${addedString}"`

exec(cmd)
