#!/bin/sh

# The world's best pastebin terminal replacement. I'm so in love.  You
# can call this from *within* vi!

if [ -n "$1" ]; then
  exec curl -s "ix.io/$1"
fi

url=$(curl -s -F 'f:1=<-' http://ix.io)
echo "$url"
echo "$url" | pbcopy
