#!/usr/bin/env bash

# brew install vlc

URL=$1
VLC=/Applications/VLC.app/Contents/MacOS/VLC

TERM=xterm-256color \
 $VLC --intf macosx --extraintf ncurses "$URL"; stty sane

# $VLC --intf http --extraintf ncurses --http-password $VLC_PASS --http-port 9999 "$URL"
