#!/usr/bin/env bash

LAMBDA_ID=indexer-platform-stack-fngrootD9A3CE0D-3XPzErihoqPW

# LAMBDA_ID_OLD=IndexerPlatformStack-fnhulk8AF9E17A-cQ4MmKFvs8QQ

aws-vault exec ironforge-dev -- \
  cw tail \
    --follow \
    /aws/lambda/$LAMBDA_ID
