#!/usr/bin/env bash

LAMBDA_ID=indexer-platform-stack-fnhulk8AF9E17A-cGUZTd4VR5Si

# LAMBDA_ID_OLD=IndexerPlatformStack-fnhulk8AF9E17A-cQ4MmKFvs8QQ

aws-vault exec ironforge-dev -- \
  aws logs tail \
    --follow \
    /aws/lambda/$LAMBDA_ID
